[versions]
plugin_kotlin = "1.8.21"
plugin_mixin = "0.7.+"
plugin_forge = "6.0.+"
plugin_parchmentmc = "1.+"


minecraft = "1.18.2"
minecraftForge = "1.18.2-40.2.0"
kotlinForForge = "3.12.0"
forge = " 40.2.0"
parchmentmc = "2022.11.06"
mixin = "0.8.5"
mixinExtras = "0.5.0-beta.4"

jei = "10.2.1.1009"
ae2 = "11.7.6"
mekanism = "1.18.2-10.2.5.465"
appmek = "3968835"
megacells = "4027408"
ae2things = "4948360"
clothConfig = "11.1.106"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
minecraftForge = { module = "net.minecraftforge:forge", version.ref = "minecraftForge" }
kotlinForForge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlinForForge" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinExtrasCommon = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinExtras" }
mixinExtrasForge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinExtras" }

jei = { module = "mezz.jei:jei-1.18.2-forge", version.ref = "jei" }
ae2 = { module = "appeng:appliedenergistics2-forge", version.ref = "ae2" }
mekanism = { module = "mekanism:Mekanism", version.ref = "mekanism" }
appmek = { module = "curse.maven:applied-mekanistics-574300", version.ref = "appmek" }
megacells = { module = "curse.maven:mega-cells-622112", version.ref = "megacells" }
ae2things = { module = "curse.maven:ae2-things-forge-609977", version.ref = "ae2things" }
clothConfig = { module = "me.shedaniel.cloth:cloth-config-forge", version.ref = "clothConfig" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin_kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin_kotlin" }
mixin = { id = "org.spongepowered.mixin", version.ref = "plugin_mixin" }
forge = { id = "net.minecraftforge.gradle", version.ref = "plugin_forge" }
parchmentmc = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "plugin_parchmentmc" }
